server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
      
message: "Hello Guys . How are you ?"

database:
  driverClass: org.h2.Driver
  user: sa
  password : sa
  url: jdbc:h2:mem:employeedb;DB_CLOSE_DELAY=-1
  properties:
    charSet: UTF-8
    maxWaitForConnection: 1s   
    minSize: 8
    maxSize: 32
    checkConnectionWhileIdle: false
    evictionInterval: 10s
    minIdleTime: 1 minute